import NavLinks from './components/nav-links';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="p-6">
        <header className="mb-8">
          <NavLinks />
        </header>
        {children}
      </body>
    </html>
  );
}
